#!/usr/bin/env python3
"""Emit the results tables as LaTeX, straight from the stored run artefacts.

The thesis \\input{}s these rather than containing typed numbers, so a figure in
the document cannot disagree with the experiment that produced it. Re-run after
any new experiment completes.

Output: thesis/chapters/generated/*.tex
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from ham10000.constants import (  # noqa: E402
    ARCHITECTURE_LABELS, CLASS_NAMES, CONFIRMATORY_EXPERIMENTS,
    EXPERIMENTS, STRATEGY_LABELS,
)

RUNS = ROOT / "runs"
OUT = ROOT / "thesis" / "chapters" / "generated"
RQ1_THRESHOLD = 0.05


def done(exp: str) -> bool:
    return (RUNS / exp / "test_metrics.json").exists()


def metrics(exp: str) -> dict:
    return json.loads((RUNS / exp / "test_metrics.json").read_text())


def rep(exp: str, cls: str, field: str) -> float:
    entry = metrics(exp)["classification_report"].get(str(CLASS_NAMES.index(cls)))
    return float(entry[field]) if entry else 0.0


def rq2(exp: str) -> float:
    return (rep(exp, "mel", "recall") + rep(exp, "bcc", "recall")) / 2


def epochs(exp: str) -> int:
    p = RUNS / exp / "history.csv"
    return len(pd.read_csv(p)) if p.exists() else 0


def label(exp: str) -> str:
    e = EXPERIMENTS[exp]
    arch = ARCHITECTURE_LABELS[e["architecture"]]
    strat = {"augmentation": "aug", "weighted_ce": "weighted CE",
             "oversampling": "oversampling"}[e["strategy"]]
    size = f" @{e['image_size']}" if e["architecture"] == "efficientnet_b3" else ""
    return f"{arch}{size} + {strat}"


def bold_max(values, fmt="{:.3f}"):
    """Format a column, bolding the largest value."""
    top = max(values)
    return [(r"\textbf{" + fmt.format(v) + "}") if v == top else fmt.format(v)
            for v in values]


def wrap(body: str, caption: str, tag: str, cols: str, header: str,
         size: str = r"\small") -> str:
    return (
        "% Generated by scripts/build_thesis_tables.py -- do not edit by hand.\n"
        "\\begin{table}[htbp]\n\\centering\n"
        f"\\caption{{{caption}}}\n\\label{{tab:{tag}}}\n{size}\n"
        f"\\begin{{tabular}}{{@{{}}{cols}@{{}}}}\n\\toprule\n"
        f"{header}\n\\midrule\n{body}\\bottomrule\n"
        "\\end{tabular}\n\\end{table}\n"
    )


def table_headline(exps):
    acc = [metrics(e)["accuracy"] for e in exps]
    bal = [metrics(e)["balanced_accuracy"] for e in exps]
    mf1 = [metrics(e)["macro_f1"] for e in exps]
    auc = [metrics(e).get("macro_auc_ovr") or 0.0 for e in exps]
    a, b, m, u = bold_max(acc), bold_max(bal), bold_max(mf1), bold_max(auc)
    rows = "".join(
        f"{e} & {label(e)} & {epochs(e)} & {a[i]} & {b[i]} & {m[i]} & {u[i]} \\\\\n"
        for i, e in enumerate(exps)
    )
    return wrap(
        rows,
        "Test-set metrics. Epochs is the number completed before early stopping. "
        "Best value in each column in bold.",
        "headline", "llrrrrr",
        r"\textbf{Exp} & \textbf{Configuration} & \textbf{Epochs} & \textbf{Accuracy} & "
        r"\textbf{Bal.\ acc.} & \textbf{Macro F1} & \textbf{Macro AUC} \\",
    )


def table_perclass(exps):
    rows = ""
    for e in exps:
        vals = [rep(e, c, "f1-score") for c in CLASS_NAMES]
        cells = []
        for c, v in zip(CLASS_NAMES, vals):
            s = f"{v:.3f}"
            cells.append(r"\textbf{" + s + "}" if c in ("mel", "bcc") else s)
        rows += f"{e} & " + " & ".join(cells) + " \\\\\n"
    header = r"\textbf{Exp} & " + " & ".join(
        r"\textbf{" + c.upper() + "}" for c in CLASS_NAMES) + r" \\"
    return wrap(
        rows,
        "Per-class F1 for all seven classes. The two clinical classes are in bold.",
        "perclass", "l" + "c" * len(CLASS_NAMES), header, size=r"\scriptsize",
    )


def table_clinical(exps):
    scores = [rq2(e) for e in exps]
    best = max(scores)
    rows = ""
    for e, sc in zip(exps, scores):
        cells = [f"{rep(e, c, f):.3f}" for c in ("mel", "bcc")
                 for f in ("precision", "recall", "f1-score")]
        s = f"{sc:.3f}"
        rows += f"{e} & " + " & ".join(cells) + " & " + \
                (r"\textbf{" + s + "}" if sc == best else s) + " \\\\\n"
    header = (
        r"& \multicolumn{3}{c}{\textbf{Melanoma}} & \multicolumn{3}{c}{\textbf{BCC}} & \\"
        "\n\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\n"
        r"\textbf{Exp} & \textbf{P} & \textbf{R} & \textbf{F1} & \textbf{P} & "
        r"\textbf{R} & \textbf{F1} & \textbf{RQ2 score} \\"
    )
    return wrap(
        rows,
        "Precision, recall and F1 on the two clinical classes. The final column is the "
        "RQ2 selection criterion, the unweighted mean of the two recall values.",
        "clinical", "lcccccc c", header,
    )


def table_rq2(exps):
    archs, strats = [], ["augmentation", "weighted_ce", "oversampling"]
    for e in exps:
        a = EXPERIMENTS[e]["architecture"]
        if a not in archs:
            archs.append(a)
    rows = ""
    for a in archs:
        members = [e for e in exps if EXPERIMENTS[e]["architecture"] == a]
        if not members:
            continue
        best = max(members, key=rq2)
        cells = []
        for s in strats:
            hit = [e for e in members if EXPERIMENTS[e]["strategy"] == s]
            if not hit:
                cells.append("--")
                continue
            e = hit[0]
            txt = f"{rq2(e):.3f} ({e})"
            cells.append(r"\textbf{" + txt + "}" if e == best else txt)
        sizes = {EXPERIMENTS[e]["image_size"] for e in members}
        name = ARCHITECTURE_LABELS[a] + (f" @{min(sizes)}" if len(sizes) == 1
                                         and a == "efficientnet_b3" else "")
        rows += f"{name} & " + " & ".join(cells) + " \\\\\n"
    return wrap(
        rows,
        "RQ2 criterion by architecture and strategy. Best per architecture in bold.",
        "rq2", "lccc",
        r"& \textbf{Augmentation only} & \textbf{Weighted CE} & \textbf{Oversampling} \\",
    )


def table_mcnemar():
    p = RUNS / "mcnemar_results.csv"
    if not p.exists():
        return None
    df = pd.read_csv(p)
    out = ""
    for fam in ("confirmatory", "exploratory"):
        sub = df[df.family == fam]
        if sub.empty:
            continue
        rows = ""
        for _, r in sub.iterrows():
            pv = r["p_holm_corrected"]
            ptxt = f"{pv:.3g}" if pv >= 1e-4 else f"{pv:.2e}".replace("e-0", "e--").replace("e-", "e--")
            rows += (f"{r['exp_a']} vs {r['exp_b']} & {ptxt} & "
                     f"{'Yes' if r['reject_at_0.05'] else 'No'} & {r['better']} \\\\\n")
        n_sig = int(sub["reject_at_0.05"].sum())
        out += wrap(
            rows,
            f"McNemar's test, {fam} family, Holm-Bonferroni corrected at "
            f"$\\alpha = 0.05$. {n_sig} of {len(sub)} comparisons reach significance.",
            f"mcnemar-{fam}", "lrrl",
            r"\textbf{Comparison} & \textbf{$p$ (Holm)} & \textbf{Significant} & "
            r"\textbf{Favours} \\",
        ) + "\n"
    return out or None


def table_efficiency():
    """Two hosts, because the ranking is not the same on both.

    MobileNetV2 is fastest everywhere, but ResNet-50 and EfficientNet-B3 swap
    places between ARM and x86_64. Reporting one host would state a conclusion
    that does not hold on the other.
    """
    hosts = [("runs/efficiency_arm64.json", "ARM64"),
             ("runs/efficiency_x86_64.json", "x86-64")]
    have = [(RUNS.parent / f, lab) for f, lab in hosts if (RUNS.parent / f).exists()]
    if not have:
        return None

    data = {lab: json.loads(p.read_text()) for p, lab in have}
    first = next(iter(data.values()))
    rows = ""
    for r in first["results"]:
        name = ARCHITECTURE_LABELS[r["architecture"]]
        if r["architecture"] == "efficientnet_b3":
            name += f" @{r['image_size']}"
        cells = [name, f"{r['trainable_params']:,}", f"{r['state_dict_mb']:.2f}"]
        for lab in data:
            d = data[lab]
            m = next(x for x in d["results"]
                     if x["architecture"] == r["architecture"]
                     and x["image_size"] == r["image_size"])
            base = next(x for x in d["results"] if x["architecture"] == "mobilenet_v2")
            cells.append(f"{m['cpu_latency_ms_mean']:.1f} ({m['cpu_latency_ms_mean']/base['cpu_latency_ms_mean']:.1f}x)")
        rows += " & ".join(cells) + " \\\\\n"

    labs = " & ".join(r"\textbf{" + l + "}" for l in data)
    return wrap(
        rows,
        "RQ3 efficiency. Latency is milliseconds per image at batch size 1 on one CPU "
        "thread, mean of 100 timed runs after 10 warm-up iterations, with the ratio to "
        "MobileNetV2 in brackets. Measured on two CPU architectures because the ordering "
        "of ResNet-50 and EfficientNet-B3 is not the same on both.",
        "efficiency", "lrr" + "r" * len(data),
        r"\textbf{Architecture} & \textbf{Params} & \textbf{Size (MB)} & " + labs + r" \\",
    )


def macros(exps):
    """\\newcommand definitions so inline prose can cite generated numbers too."""
    lines = ["% Generated by scripts/build_thesis_tables.py -- do not edit by hand."]
    conf = [e for e in exps if e in CONFIRMATORY_EXPERIMENTS]
    mob = [e for e in conf if EXPERIMENTS[e]["architecture"] == "mobilenet_v2"]
    res = [e for e in conf if EXPERIMENTS[e]["architecture"] == "resnet50"]
    if mob and res:
        bm, br = max(mob, key=rq2), max(res, key=rq2)
        gap = abs(rep(bm, "mel", "f1-score") - rep(br, "mel", "f1-score"))
        am = max(mob, key=lambda e: metrics(e)["macro_f1"])
        ar = max(res, key=lambda e: metrics(e)["macro_f1"])
        altgap = abs(rep(am, "mel", "f1-score") - rep(ar, "mel", "f1-score"))
        for name, val in [
            ("RQoneBestMobile", bm), ("RQoneBestResnet", br),
            ("RQoneFoneMobile", f"{rep(bm, 'mel', 'f1-score'):.3f}"),
            ("RQoneFoneResnet", f"{rep(br, 'mel', 'f1-score'):.3f}"),
            ("RQoneGap", f"{gap:.3f}"),
            ("RQoneVerdict", "passes" if gap <= RQ1_THRESHOLD else "fails"),
            ("RQoneAltMobile", am), ("RQoneAltResnet", ar),
            ("RQoneAltGap", f"{altgap:.3f}"),
            ("RQtwoBestMobile", max(mob, key=rq2)),
            ("RQtwoBestResnet", max(res, key=rq2)),
            ("NumRunsDone", str(len(exps))),
        ]:
            lines.append(f"\\newcommand{{\\{name}}}{{{val}}}")
    return "\n".join(lines) + "\n"


def main() -> None:
    exps = [e for e in EXPERIMENTS if done(e)]
    if not exps:
        print("no completed runs")
        return
    OUT.mkdir(parents=True, exist_ok=True)
    print(f"generating from {len(exps)} runs: {', '.join(exps)}")

    written = {
        "headline.tex": table_headline(exps),
        "perclass.tex": table_perclass(exps),
        "clinical.tex": table_clinical(exps),
        "rq2.tex": table_rq2(exps),
        "macros.tex": macros(exps),
    }
    mc = table_mcnemar()
    if mc:
        written["mcnemar.tex"] = mc
    eff = table_efficiency()
    if eff:
        written["efficiency.tex"] = eff

    for name, body in written.items():
        (OUT / name).write_text(body)
        print(f"  chapters/generated/{name}")


if __name__ == "__main__":
    main()
